
package View;

import Controller.AccountController;
import Model.Account;
import Model.Session;
import javax.swing.JOptionPane;



public class ChangePassWordDialog extends javax.swing.JDialog {

     private AccountController accountController;
     
     public ChangePassWordDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          accountController = new AccountController();
          
          setLocationRelativeTo(parent);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel4 = new javax.swing.JLabel();
          txtOldPass = new javax.swing.JPasswordField();
          txtNewPass = new javax.swing.JPasswordField();
          txtConfirm = new javax.swing.JPasswordField();
          btnCancel = new custom.Button();
          btnSave = new custom.Button();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel4.setText("Xác nhận mật khẩu mới");

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          btnSave.setBackground(new java.awt.Color(0, 153, 255));
          btnSave.setForeground(new java.awt.Color(255, 255, 255));
          btnSave.setText("Lưu");
          btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnSave.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSaveActionPerformed(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel1.setText("Đổi Mật Khẩu");

          jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel2.setText("Mật khẩu hiện tại");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel3.setText("Mật khẩu mới");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(174, 174, 174)
                              .addComponent(jLabel1))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel3)
                                        .addGap(56, 56, 56))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel4)
                                             .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(txtConfirm)
                                   .addComponent(txtNewPass)
                                   .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(116, 116, 116)
                              .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(82, 82, 82)
                              .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(77, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                         .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed

     private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
          Account curAccount = Session.getCurrentUser();
          String curUser = curAccount.getUsername();
          String oldPass = curAccount.getPassword();
          String curPass = new String(txtOldPass.getPassword());
          String newPass = new String(txtNewPass.getPassword());
          String confirm = new String(txtConfirm.getPassword());

          if(!curPass.equals("")){
               if(curPass.equals(oldPass)){
                    if(!newPass.equals("")){
                         if(!confirm.equals("")){
                              if(newPass.equals(curPass)){
                                   JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mật khẩu mới không trùng với hiện tại!");
                              }
                              else if(newPass.equals(confirm)){
                                   if(accountController.changePassWord(curUser, newPass)){
                                        JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công!");
                                        txtOldPass.setText("");
                                        txtNewPass.setText("");
                                        txtConfirm.setText("");
                                   }
                                   else{
                                        JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thất bại!");
                                   }
                              }
                              else{
                                   JOptionPane.showMessageDialog(rootPane, "Mật khẩu xác nhận không chính xác!");
                              }
                         }
                         else{
                              JOptionPane.showMessageDialog(rootPane, "Vui lòng xác nhận mật khẩu mới!");
                         }
                    }
                    else{
                         JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mật khẩu mới!");
                    }
               }
               else{
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng mật khẩu hiện tại!");
               }
          }
          else{
               JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mật khẩu hiện tại!");
          }
     }//GEN-LAST:event_btnSaveActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ChangePassWordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ChangePassWordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ChangePassWordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ChangePassWordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    ChangePassWordDialog dialog = new ChangePassWordDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnSave;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JPasswordField txtConfirm;
     private javax.swing.JPasswordField txtNewPass;
     private javax.swing.JPasswordField txtOldPass;
     // End of variables declaration//GEN-END:variables
}
