
package View;

import Model.Contract;
import Model.Shop;
import Model.ContractDAO;
import Controller.ShopController;
import Controller.ContractController;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTargetAdapter;

public class ControlContract extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControlContract.class.getName());

    private ContractDAO contractDAO = new ContractDAO();
    private ShopController shopController = new ShopController();
    private ContractController contractController = new ContractController();
    
     DefaultTableModel model;
    
    public ControlContract() {
        initComponents();
        
        // chỉnh độ rộng cột ở đây
          tableContract.getColumnModel().getColumn(0).setPreferredWidth(100);
          tableContract.getColumnModel().getColumn(1).setPreferredWidth(180);
          tableContract.getColumnModel().getColumn(2).setPreferredWidth(140);
          tableContract.getColumnModel().getColumn(3).setPreferredWidth(100);
          tableContract.getColumnModel().getColumn(4).setPreferredWidth(180);
          tableContract.getColumnModel().getColumn(4).setPreferredWidth(200);
        
         setLocationRelativeTo(null);
         
         model = (DefaultTableModel) tableContract.getModel();
         
         loadData();
    }

    private void loadData(){
         model.setRowCount(0);
         List<Contract> list = contractDAO.getAllContracts();
         for (Contract c : list) {
               Shop s = shopController.getShopById(c.getShopId());
               model.addRow(new Object[]{
                   c.getContractId(),
                   c.getName(),
                   c.getShopName(),
                   s.getArea(),
                   c.getIncome() + " VNĐ",
                   c.status.equals("active") ? "Còn hạn" : "Sắp hết hạn"
               });
         }
    }
    
    public void closeWithEffect(JFrame currentFrame, Runnable afterCloseAction) {
          Animator animator = new Animator(1500, new TimingTargetAdapter() {
              @Override
              public void timingEvent(float fraction){
                  background1.setAnimate(fraction);
              }

              @Override
              public void end() {
                  currentFrame.dispose();
                  if (afterCloseAction != null) {
                      afterCloseAction.run();
                  }
              }
          });
          animator.start();
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jColorChooser1 = new javax.swing.JColorChooser();
          background1 = new custom.Background();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tableContract = new javax.swing.JTable();
          btnGiaHan = new custom.Button();
          btnSua = new custom.Button();
          btnDeleteContract = new custom.Button();
          btnAddContract = new custom.Button();
          btnExit = new custom.Button();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Quản Lý Hợp Đồng");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel3.setText("Danh sách hợp đồng");

          tableContract.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          tableContract.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null}
               },
               new String [] {
                    "Mã hợp đồng", "Tên khách thuê", "Tên shop", "Khu vực", "Tiền thuê / tháng", "Trạng thái"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tableContract.setToolTipText("");
          tableContract.setRowHeight(40);
          tableContract.getTableHeader().setFont(new java.awt.Font("Time New Roman", java.awt.Font.BOLD, 14));
          jScrollPane1.setViewportView(tableContract);

          btnGiaHan.setBackground(new java.awt.Color(0, 153, 255));
          btnGiaHan.setForeground(new java.awt.Color(255, 255, 255));
          btnGiaHan.setText("Gia hạn hợp đồng");
          btnGiaHan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnGiaHan.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGiaHanActionPerformed(evt);
               }
          });

          btnSua.setBackground(new java.awt.Color(0, 153, 255));
          btnSua.setForeground(new java.awt.Color(255, 255, 255));
          btnSua.setText("Sửa tiền thuê");
          btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnSua.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSuaActionPerformed(evt);
               }
          });

          btnDeleteContract.setBackground(new java.awt.Color(0, 153, 255));
          btnDeleteContract.setForeground(new java.awt.Color(255, 255, 255));
          btnDeleteContract.setText("Hủy hợp đồng");
          btnDeleteContract.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnDeleteContract.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDeleteContractActionPerformed(evt);
               }
          });

          btnAddContract.setBackground(new java.awt.Color(0, 153, 255));
          btnAddContract.setForeground(new java.awt.Color(255, 255, 255));
          btnAddContract.setText("Thêm hợp đồng");
          btnAddContract.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnAddContract.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAddContractActionPerformed(evt);
               }
          });

          btnExit.setBackground(new java.awt.Color(0, 153, 255));
          btnExit.setForeground(new java.awt.Color(255, 255, 255));
          btnExit.setText("Thoát");
          btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnExit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnExitActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
          background1.setLayout(background1Layout);
          background1Layout.setHorizontalGroup(
               background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(background1Layout.createSequentialGroup()
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(background1Layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(345, 345, 345)
                              .addComponent(jLabel2))
                         .addGroup(background1Layout.createSequentialGroup()
                              .addGap(203, 203, 203)
                              .addComponent(jLabel3)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                              .addComponent(btnGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnDeleteContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnAddContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(148, 148, 148))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(83, 83, 83))))
          );
          background1Layout.setVerticalGroup(
               background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(background1Layout.createSequentialGroup()
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(background1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel2))
                         .addComponent(jLabel1))
                    .addGap(17, 17, 17)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnAddContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnDeleteContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(136, 136, 136))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaHanActionPerformed
          ExtendContractDialog dlg = new ExtendContractDialog(this, true);
            dlg.setVisible(true);
         contractController.cancelExpiredContracts();
         contractController.updateContractStatuses();
         loadData();
     }//GEN-LAST:event_btnGiaHanActionPerformed

     private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
          UpdateIncomeDialog updateIncomeDialog = new UpdateIncomeDialog(this, true);
          updateIncomeDialog.setVisible(true);
          loadData();
     }//GEN-LAST:event_btnSuaActionPerformed

     private void btnDeleteContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContractActionPerformed
          DeleteContractDialog dlg = new DeleteContractDialog(this, true);
            dlg.setVisible(true);
            loadData();
     }//GEN-LAST:event_btnDeleteContractActionPerformed

     private void btnAddContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContractActionPerformed
          NewContractDialog dlg = new NewContractDialog(this, true);
            dlg.setVisible(true);
         contractController.cancelExpiredContracts();
         contractController.updateContractStatuses();
         loadData();
     }//GEN-LAST:event_btnAddContractActionPerformed

     private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
          closeWithEffect(this, () -> new MainView_Admin().setVisible(true));
     }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ControlContract().setVisible(true));
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Background background1;
     private custom.Button btnAddContract;
     private custom.Button btnDeleteContract;
     private custom.Button btnExit;
     private custom.Button btnGiaHan;
     private custom.Button btnSua;
     private javax.swing.JColorChooser jColorChooser1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable tableContract;
     // End of variables declaration//GEN-END:variables
}
