
package View;


import Model.Shop;
import Model.Tenant;
import Model.Contract;
import Model.ContractDAO;
import Controller.ShopController;
import Controller.TenantController;

public class ContractDialog extends javax.swing.JDialog {

     private int tenantId;
     private TenantController tenantController = new TenantController();
     private ShopController shopController = new ShopController();
     
     public ContractDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
     }

     public ContractDialog(java.awt.Frame parent, boolean modal, int tenantId) {
          super(parent, modal);
          initComponents();
          
     
          this.tenantId = tenantId;
          
          setLocationRelativeTo(null);
          
          loadDatas();
     }
     
     private void loadDatas(){
          Tenant curTenant = tenantController.getTenant(tenantId);
          
          lblTenantName.setText(curTenant.getTenantName());
          lblSDTTenant.setText(curTenant.getPhone());
          lblEmailTenant.setText(curTenant.getEmail());
          
          int shopId = curTenant.getShopId();
          Shop s = shopController.getShopById(shopId);
          if(s!=null){
               lblShop.setText(s.getName());
               lblArea.setText(s.getArea());
          }
          else{
               lblShop.setText("Chưa thuê");
               lblArea.setText("Chưa thuê");
          }
          int contractId = curTenant.getContractId();
          Contract c = ContractDAO.findById(contractId);
          if(c!=null){
               lblContractId.setText(Integer.toString(c.getContractId()));
               lblStartDate.setText(c.getStartDate().toString());
               lblEndDate.setText(c.getEndDate().toString());
               lblRental.setText(c.getIncome().toString() + " VNĐ");
          }
     }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btnClose = new custom.Button();
          jLabel15 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jLabel17 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          lblAdmin = new javax.swing.JLabel();
          lblSDTAdmin = new javax.swing.JLabel();
          lblEmailAdmin = new javax.swing.JLabel();
          lblTenantName = new javax.swing.JLabel();
          lblSDTTenant = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          lblEmailTenant = new javax.swing.JLabel();
          lblShop = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          lblStartDate = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          lblEndDate = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          lblRental = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jLabel20 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          lblContractId = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jLabel14 = new javax.swing.JLabel();
          lblArea = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          btnClose.setBackground(new java.awt.Color(0, 153, 255));
          btnClose.setForeground(new java.awt.Color(255, 255, 255));
          btnClose.setText("Đóng");
          btnClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          btnClose.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCloseActionPerformed(evt);
               }
          });

          jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel16.setText("Ngày bắt đầu thuê:");

          jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel17.setText("Ngày kết thúc:");

          jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel18.setText("Tiền thuê hàng tháng:");

          lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          lblAdmin.setText("AD");

          lblSDTAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          lblSDTAdmin.setText("0363636363");

          lblEmailAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          lblEmailAdmin.setText("adminTTTM@gmail.com");
          lblEmailAdmin.setToolTipText("");

          lblTenantName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblSDTTenant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel1.setText("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel2.setText("Độc lập - Tự do - Hạnh phúc");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel3.setText("--------------------------");

          jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel4.setText("HỢP ĐỒNG CHO THUÊ GIAN HÀNG");

          lblEmailTenant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblShop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel5.setText("Bên cho thuê");

          jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel6.setText("Quản lý trung tâm thương mại:");

          lblStartDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel7.setText("Số điện thoại:");

          lblEndDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel8.setText("Email:");

          lblRental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel9.setText("Bên thuê");

          jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel20.setText("Mã hợp đồng:");

          jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel10.setText("Tên khách thuê:");

          lblContractId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

          jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel11.setText("Số điện thoại:");

          jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel12.setText("Email:");

          jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel13.setText("Shop đang thuê:");

          jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel14.setText("Khu vực:");

          lblArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36))
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(198, 198, 198)
                              .addComponent(jLabel3))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(108, 108, 108)
                              .addComponent(jLabel4))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel15)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel1))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(113, 113, 113))))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(62, 62, 62)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel7)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblSDTAdmin))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel6)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblAdmin))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel8)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblEmailAdmin))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel14)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel17)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel18)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(22, 22, 22)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel5)
                                                  .addComponent(jLabel9)))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel16)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel10)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblTenantName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel13)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblShop, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel11)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblSDTTenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel12)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(lblEmailTenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addContainerGap(35, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel2))
                         .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel20)
                         .addComponent(lblContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel5)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel6)
                                   .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel7))
                         .addGroup(layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                              .addComponent(lblSDTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(lblEmailAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel9)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel10)
                                   .addComponent(lblTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel11)
                                   .addComponent(lblSDTTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel12))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(84, 84, 84)
                              .addComponent(lblEmailTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel13)
                         .addComponent(lblShop, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel14)
                         .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel16)
                                   .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel17))
                         .addComponent(lblEndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel18)
                         .addComponent(lblRental, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
          dispose();
     }//GEN-LAST:event_btnCloseActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    ContractDialog dialog = new ContractDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnClose;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JLabel lblAdmin;
     private javax.swing.JLabel lblArea;
     private javax.swing.JLabel lblContractId;
     private javax.swing.JLabel lblEmailAdmin;
     private javax.swing.JLabel lblEmailTenant;
     private javax.swing.JLabel lblEndDate;
     private javax.swing.JLabel lblRental;
     private javax.swing.JLabel lblSDTAdmin;
     private javax.swing.JLabel lblSDTTenant;
     private javax.swing.JLabel lblShop;
     private javax.swing.JLabel lblStartDate;
     private javax.swing.JLabel lblTenantName;
     // End of variables declaration//GEN-END:variables
}
