
package View;

import Model.Contract;
import Model.ContractDAO;
import Model.Tenant;
import Controller.ShopController;
import Controller.TenantController;
import Controller.ProductController;
import Controller.AccountController;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class DeleteContractDialog extends javax.swing.JDialog {

     private ShopController shopController = new ShopController();
     private TenantController tenantController = new TenantController();
     private ProductController productController = new ProductController();
     private AccountController accountController = new AccountController();
     
     public DeleteContractDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          setLocationRelativeTo(parent);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          txtContractId = new javax.swing.JTextField();
          btnExit = new custom.Button();
          btnConfirm = new custom.Button();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setText("Hủy Hợp Đồng");

          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel3.setText("Mã hợp đồng:");

          jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
          jLabel4.setText("Nhập mã hợp đồng muốn hủy");

          btnExit.setBackground(new java.awt.Color(0, 153, 255));
          btnExit.setForeground(new java.awt.Color(255, 255, 255));
          btnExit.setText("Thoát");
          btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
          btnExit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnExitActionPerformed(evt);
               }
          });

          btnConfirm.setBackground(new java.awt.Color(0, 153, 255));
          btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
          btnConfirm.setText("Xác nhận");
          btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
          btnConfirm.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConfirmActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(67, 67, 67)
                              .addComponent(jLabel1))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(54, 54, 54)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel4)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtContractId)))))
                    .addContainerGap(119, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel1))
                         .addComponent(jLabel2))
                    .addGap(19, 19, 19)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
          dispose();
     }//GEN-LAST:event_btnExitActionPerformed

     private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
          try {
               int contractId = Integer.parseInt(txtContractId.getText());
               Contract c = ContractDAO.findById(contractId);
               if (c != null) {
                   int confirm = JOptionPane.showConfirmDialog(
                         this,
                         "Bạn có chắc muốn hủy hợp đồng này?",
                         "Hủy hợp đồng",
                         JOptionPane.YES_NO_OPTION
                 );
                 if (confirm == JOptionPane.YES_OPTION) {
                    int tenantId = (int)c.getTenantId();
                    Tenant t = tenantController.getTenant(tenantId);
                    int shopId = c.getShopId();
                    String username = t.getUsername().trim();

                    //Xóa tenant
                    tenantController.deleteTenant(tenantId);

                    //cập nhật lại shop
                    shopController.updateShopAfterCancel(shopId);

                    //xóa sản phẩm trong shop bị hủy
                    productController.deleteAllProductById(shopId);

                    //xóa account
                    accountController.deleteAccountByUsername(username);

                    //xóa hợp đồng
                    ContractDAO.deleteContractById(contractId);

                    JOptionPane.showMessageDialog(this, "Hủy hợp đồng thành công!");
                 }
                 else JOptionPane.showMessageDialog(this, "Hủy thất bại!");   
                 txtContractId.setText("");
               } else {
                   JOptionPane.showMessageDialog(this, "Không tìm thấy hợp đồng!");
               }
           } catch (NumberFormatException ex) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập ID hợp đồng hợp lệ!");
           }
     }//GEN-LAST:event_btnConfirmActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(DeleteContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(DeleteContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(DeleteContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(DeleteContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    DeleteContractDialog dialog = new DeleteContractDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnConfirm;
     private custom.Button btnExit;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JTextField txtContractId;
     // End of variables declaration//GEN-END:variables
}
