
package View;

import Model.Contract;
import Model.ContractDAO;
import Controller.ContractController;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ExtendContractDialog extends javax.swing.JDialog {

     
     private ContractController contractController = new ContractController();
     
     public ExtendContractDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          setLocationRelativeTo(null);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          btnSava = new custom.Button();
          btnCancel = new custom.Button();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtContractId = new javax.swing.JTextField();
          txtExtend = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          btnSava.setBackground(new java.awt.Color(0, 153, 255));
          btnSava.setForeground(new java.awt.Color(255, 255, 255));
          btnSava.setText("Gia hạn");
          btnSava.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnSava.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSavaActionPerformed(evt);
               }
          });

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Gia hạn hợp đồng");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
          jLabel3.setText("Nhập thông tin");

          jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel4.setText("Mã hợp đồng");

          jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel5.setText("Ngày gia hạn (yyyy-mm-dd)");

          txtContractId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          txtExtend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnSava, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66))
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(51, 51, 51)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel2))))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(83, 83, 83)
                              .addComponent(jLabel3)))
                    .addContainerGap(52, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(16, 16, 16)
                              .addComponent(jLabel2)))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(txtExtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnSava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed

     private void btnSavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavaActionPerformed
          try {
               int contractId = Integer.parseInt(txtContractId.getText());
               Contract c = ContractDAO.findById(contractId);
               
               if (c != null) {
                   int confirm = JOptionPane.showConfirmDialog(
                         this,
                         "Gia hạn hợp đồng này?",
                         "Gia hạn",
                         JOptionPane.YES_NO_OPTION
                 );
                 if (confirm == JOptionPane.YES_OPTION) {
                    String status = c.getStatus();
                    if(status.equals("terminated")){
                         String extend = txtExtend.getText().trim();
                         if(extend.isEmpty()){
                              JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày gia hạn");
                         }
                         else{
                              java.sql.Date giahan = java.sql.Date.valueOf(extend);
                              if(giahan.before(c.getEndDate())){
                                   JOptionPane.showMessageDialog(this, "Gia hạn phải sau ngày kết thúc!");
                              }
                              else{
                                   contractController.extendContract(contractId, giahan);

                                   JOptionPane.showMessageDialog(this, "Gia hạn thành công!");
                              }
                         }
                    }
                    else{
                         JOptionPane.showMessageDialog(this, "Chỉ gia hạn được các hợp đồng sắp hết hạn!");
                    }

                 }
                 else JOptionPane.showMessageDialog(this, "Gia hạn thất bại!");   
                 txtContractId.setText("");
                 txtExtend.setText("");
               } else {
                   JOptionPane.showMessageDialog(this, "Không tìm thấy hợp đồng!");
               }
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin hợp lệ!");
           }
     }//GEN-LAST:event_btnSavaActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    ExtendContractDialog dialog = new ExtendContractDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnSava;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JTextField txtContractId;
     private javax.swing.JTextField txtExtend;
     // End of variables declaration//GEN-END:variables
}
