
package View;

import Model.Contract;
import Model.ContractDAO;
import Model.Extend;
import Controller.ContractController;
import Controller.ExtendController;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ExtendContractDialog extends javax.swing.JDialog {

     
     private ContractController contractController = new ContractController();
     private ExtendController extendController = new ExtendController();
     
     DefaultTableModel model;
     
     public ExtendContractDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          //chỉnh đọ rộng cột
          tableExtend.getColumnModel().getColumn(0).setPreferredWidth(100);
          tableExtend.getColumnModel().getColumn(1).setPreferredWidth(180);
          
          setLocationRelativeTo(null);
          initComboDate();
          
          model = (DefaultTableModel) tableExtend.getModel();
          loadData();
     }

     private void initComboDate(){
         //Ngày
         for(int i=1; i<=31; i++){
              cboDay.addItem(String.valueOf(i));
         }
         
         // Tháng
         for (int i = 1; i <= 12; i++) {
               cboMonth.addItem(String.valueOf(i));
         }

         // Năm
         int currentYear = LocalDate.now().getYear();
         for (int y = currentYear; y <= currentYear + 10; y++) {
               cboYear.addItem(String.valueOf(y));
         }

         cboDay.setSelectedItem(String.valueOf(LocalDate.now().getDayOfMonth()));
         cboMonth.setSelectedItem(String.valueOf(LocalDate.now().getMonthValue()));
         cboYear.setSelectedItem(String.valueOf(currentYear));
    }
     
     private void loadData(){
          model.setRowCount(0);
          List<Extend> lst = extendController.getListRequirements();
          for(Extend extend : lst){
               Contract contract = ContractDAO.findById(extend.getContractId());
               
               model.addRow(new Object[]{
                   extend.getContractId(),
                   contract.getEndDate()
               });
          }
     }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          btnSava = new custom.Button();
          btnCancel = new custom.Button();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtContractId = new javax.swing.JTextField();
          cboDay = new javax.swing.JComboBox<>();
          cboMonth = new javax.swing.JComboBox<>();
          cboYear = new javax.swing.JComboBox<>();
          jScrollPane1 = new javax.swing.JScrollPane();
          tableExtend = new javax.swing.JTable();
          jLabel6 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          btnSava.setBackground(new java.awt.Color(0, 153, 255));
          btnSava.setForeground(new java.awt.Color(255, 255, 255));
          btnSava.setText("Gia hạn");
          btnSava.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnSava.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSavaActionPerformed(evt);
               }
          });

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Gia hạn hợp đồng");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
          jLabel3.setText("Nhập thông tin");

          jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel4.setText("Mã hợp đồng");

          jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel5.setText("Ngày gia hạn");

          txtContractId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          tableExtend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          tableExtend.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String [] {
                    "Mã hợp đồng", "Ngày hết hạn"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tableExtend.setRowHeight(40);
          jScrollPane1.setViewportView(tableExtend);

          jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel6.setText("Danh sách yêu cầu gia hạn");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(154, 154, 154)
                              .addComponent(jLabel2))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(93, 93, 93)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel5)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                  .addComponent(cboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                  .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel4)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                  .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addComponent(jLabel3))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(107, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                   .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGap(18, 18, 18)
                                   .addComponent(btnSava, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGap(66, 66, 66))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGap(89, 89, 89)))))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(17, 17, 17)
                              .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(cboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnSava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed

     private void btnSavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavaActionPerformed
          try {
               int contractId = Integer.parseInt(txtContractId.getText());
               Contract c = ContractDAO.findById(contractId);
               Extend e = extendController.getById(contractId);
               
               if (c != null) {
                   int confirm = JOptionPane.showConfirmDialog(
                         this,
                         "Gia hạn hợp đồng này?",
                         "Gia hạn",
                         JOptionPane.YES_NO_OPTION
                 );
                 if (confirm == JOptionPane.YES_OPTION) {
                    String status = c.getStatus();
                    if(status.equals("terminated")){
                         String extend = cboYear.getSelectedItem().toString() + "-" + cboMonth.getSelectedItem().toString() + "-" + cboDay.getSelectedItem().toString();
                         java.sql.Date giahan = java.sql.Date.valueOf(extend);
                         if(giahan.before(c.getEndDate())){
                              JOptionPane.showMessageDialog(this, "Gia hạn phải sau ngày kết thúc!");
                         }
                         else if(e.getStatus().equals("no")){
                              JOptionPane.showMessageDialog(this, "Hợp đồng này chưa có yêu cầu gia hạn!");
                         }
                         else{
                              contractController.extendContract(contractId, giahan);
                              extendController.setStatusById(contractId, "no");
                              
                              JOptionPane.showMessageDialog(this, "Gia hạn thành công!");
                         }
                    }
                    else{
                         JOptionPane.showMessageDialog(this, "Chỉ gia hạn được các hợp đồng sắp hết hạn!");
                    }

                 }
                 else JOptionPane.showMessageDialog(this, "Gia hạn thất bại!");   
                 txtContractId.setText("");
//                 initComboDate();
                 loadData();
               }
               else{
                   JOptionPane.showMessageDialog(this, "Không tìm thấy hợp đồng!");
               }
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin hợp lệ!");
           }
     }//GEN-LAST:event_btnSavaActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ExtendContractDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    ExtendContractDialog dialog = new ExtendContractDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnSava;
     private javax.swing.JComboBox<String> cboDay;
     private javax.swing.JComboBox<String> cboMonth;
     private javax.swing.JComboBox<String> cboYear;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable tableExtend;
     private javax.swing.JTextField txtContractId;
     // End of variables declaration//GEN-END:variables
}
