
package View;

import Controller.ShopController;
import Controller.TenantController;
import Model.Contract;
import Model.Session;
import Model.Shop;
import Model.Tenant;
import Model.ContractDAO;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;



public class InfoTenantDialog extends javax.swing.JDialog {

     private TenantController tenantController = new TenantController();
     private ShopController shopController = new ShopController();
     private ContractDAO contractDAO = new ContractDAO();
     private int tenantId;
     
     public InfoTenantDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          setLocationRelativeTo(parent);
          
          loadInfo();
     }

     private void loadInfo(){
          this.tenantId = Session.getCurrentTenantId();
          Tenant curTenant = tenantController.getTenant(tenantId);
          lblId.setText(Integer.toString(tenantId));
          lblName.setText(curTenant.getTenantName());
          lblSDT.setText(curTenant.getPhone());
          lblEmail.setText(curTenant.getEmail());
          
          int shopId = curTenant.getShopId();
          Shop s = shopController.getShopById(shopId);
          if(s!=null){
               lblShop.setText(s.getName());
               lblArea.setText(s.getArea());
          }
          else{
               lblShop.setText("Chưa thuê");
               lblArea.setText("Chưa thuê");
          }
          
          int contractId = curTenant.getContractId();
          Contract c = ContractDAO.findById(contractId);
          if(c!=null){
               String status = c.getStatus();
               if(status.equals("active")){
                    lblStatus.setForeground(new Color(76, 175, 80));
                    lblStatus.setText("Còn hạn");
               }
               else{
                    lblStatus.setForeground(new Color(255, 193, 7));
                    lblStatus.setText("Sắp hết hạn");
               }
          }
     }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btnHopDong = new custom.Button();
          lblEmail = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          lblShop = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          lblArea = new javax.swing.JLabel();
          btnClose = new custom.Button();
          jLabel6 = new javax.swing.JLabel();
          lblId = new javax.swing.JLabel();
          lblSDT = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          lblName = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          btnUpdate = new custom.Button();
          jLabel9 = new javax.swing.JLabel();
          lblStatus = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          btnHopDong.setBackground(new java.awt.Color(0, 153, 255));
          btnHopDong.setForeground(new java.awt.Color(255, 255, 255));
          btnHopDong.setText("Hợp đồng");
          btnHopDong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnHopDong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnHopDongActionPerformed(evt);
               }
          });

          lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel3.setText("Tên:");

          lblShop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel5.setText("Email:");

          jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel4.setText("Số điện thoại:");

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
          jLabel1.setText("Thông tin cá nhân");

          lblArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          btnClose.setBackground(new java.awt.Color(0, 153, 255));
          btnClose.setForeground(new java.awt.Color(255, 255, 255));
          btnClose.setText("Đóng");
          btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnClose.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCloseActionPerformed(evt);
               }
          });

          jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel6.setText("Shop đang thuê:");

          lblId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel7.setText("Khu vực:");

          lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

          jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel2.setText("Mã khách thuê:");

          btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
          btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
          btnUpdate.setText("Sửa thông tin");
          btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnUpdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUpdateActionPerformed(evt);
               }
          });

          jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
          jLabel9.setText("Trạng thái hợp đồng:");

          lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel8)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(jLabel1))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel6)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(lblShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addGroup(layout.createSequentialGroup()
                                                       .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                       .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                  .addGroup(layout.createSequentialGroup()
                                                       .addComponent(jLabel5)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                       .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                  .addComponent(jLabel7)
                                                  .addGroup(layout.createSequentialGroup()
                                                       .addComponent(jLabel2)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                       .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                       .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                       .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                             .addGroup(layout.createSequentialGroup()
                                                  .addGap(79, 79, 79)
                                                  .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel9)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(149, 149, 149)
                              .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(63, 63, 63)
                              .addComponent(btnHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(39, 39, 39)
                              .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(125, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel8)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                   .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel4))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel5))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel6)
                                   .addComponent(lblShop, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDongActionPerformed
          new ContractDialog((Frame) getParent(), true ,tenantId).setVisible(true);
     }//GEN-LAST:event_btnHopDongActionPerformed

     private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
          dispose();
     }//GEN-LAST:event_btnCloseActionPerformed

     private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          int confirm = JOptionPane.showConfirmDialog(this,
               "Cập nhật thông tin?",
               "Xác nhận", JOptionPane.YES_NO_OPTION);
          if(confirm == JOptionPane.YES_OPTION){
               UpdateInfoDialog dialog = new UpdateInfoDialog((Frame) getParent(), true, tenantId);
               dialog.setVisible(true);
               loadInfo();
          }
          else{
               JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
          }
     }//GEN-LAST:event_btnUpdateActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(InfoTenantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(InfoTenantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(InfoTenantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(InfoTenantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    InfoTenantDialog dialog = new InfoTenantDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnClose;
     private custom.Button btnHopDong;
     private custom.Button btnUpdate;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JLabel lblArea;
     private javax.swing.JLabel lblEmail;
     private javax.swing.JLabel lblId;
     private javax.swing.JLabel lblName;
     private javax.swing.JLabel lblSDT;
     private javax.swing.JLabel lblShop;
     private javax.swing.JLabel lblStatus;
     // End of variables declaration//GEN-END:variables
}
