
package View;

import Model.Account;
import Model.AccountDAO;
import Model.Session;
import Controller.LoginController;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

public class LoginView extends javax.swing.JFrame {

     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());
     
     private AccountDAO accountDAO;
     private LoginController controller;
     
     public LoginView() {
          initComponents();

          
          controller = new LoginController();
          accountDAO = new AccountDAO();
          
          setLocationRelativeTo(null);
          
          // Nút enter như là singin
          

     }

     public void closeWithEffect(JFrame currentFrame, Runnable afterCloseAction) {
          Animator animator = new Animator(1500, new TimingTargetAdapter() {
              @Override
              public void timingEvent(float fraction){
                  background1.setAnimate(fraction);
              }

              @Override
              public void end() {
                  currentFrame.dispose();
                  if (afterCloseAction != null) {
                      afterCloseAction.run();
                  }
              }
          });
          animator.start();
      }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          background1 = new custom.Background();
          panelLogin = new custom.Background();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          textUser = new custom.TextField();
          textPass = new custom.PasswordField();
          cmdsignIn = new custom.Button();
          btnQuit = new custom.Button();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          background1.setLayout(new java.awt.CardLayout());

          jLabel1.setBackground(new java.awt.Color(255, 255, 255));
          jLabel1.setForeground(new java.awt.Color(255, 255, 255));
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logo.png"))); // NOI18N

          textUser.setLabelText("User Name");
          textUser.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textUserActionPerformed(evt);
               }
          });

          textPass.setLabelText("Password");
          textPass.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textPassActionPerformed(evt);
               }
          });

          cmdsignIn.setBackground(new java.awt.Color(0, 51, 255));
          cmdsignIn.setForeground(new java.awt.Color(255, 255, 255));
          cmdsignIn.setText("Sign In");
          cmdsignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          cmdsignIn.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmdsignInActionPerformed(evt);
               }
          });

          btnQuit.setBackground(new java.awt.Color(0, 51, 255));
          btnQuit.setForeground(new java.awt.Color(255, 255, 255));
          btnQuit.setText("Quit");
          btnQuit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
          btnQuit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnQuitActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(textUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                   .addComponent(textPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(63, 63, 63)
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(cmdsignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                    .addComponent(cmdsignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );

          javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
          panelLogin.setLayout(panelLoginLayout);
          panelLoginLayout.setHorizontalGroup(
               panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                    .addContainerGap(287, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(278, 278, 278))
          );
          panelLoginLayout.setVerticalGroup(
               panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelLoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE))
          );

          background1.add(panelLogin, "card2");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_textUserActionPerformed

     private void textPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_textPassActionPerformed

     private void cmdsignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsignInActionPerformed

          String user = textUser.getText().trim();
          String pass = String.valueOf(textPass.getPassword());
          boolean action = true;

          if (user.equals("")) {
              textUser.setHelperText("Please input User name");
              textPass.grabFocus();
              action = false;
          }
          if (pass.equals("")) {
              textPass.setHelperText("Please input Password");
              if (action) {
                  textPass.grabFocus();
              }
              action = false;
          }

          if (action) {
              boolean success = controller.login(user, pass);
              if(success){
                    // LOGIN THÀNH CÔNG - CHẠY ANIMATION
                    String name = controller.getFullName(user);
                    javax.swing.JOptionPane.showMessageDialog(this, "Login success! Welcome " + name);

                    //Xử lý lưu role của account vừa đăng nhập
                    Account curAcc = controller.getCurrentAccount(user);
                    Session.setCurrentUser(curAcc);
                    
                    if(Session.isAdmin()){
                         closeWithEffect(this, () -> new MainView_Admin().setVisible(true));
                    }
                    
                    else{
                         closeWithEffect(this, () -> new MainView_Tenant().setVisible(true));
                    }
                    
                    // Clear form sau khi login thành công
                    textUser.setText("");
                    textPass.setText("");
                    textUser.grabFocus();      

              }
              else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid username or password!");
                    // KHÔNG chạy animation khi login thất bại
              }
          }
     }//GEN-LAST:event_cmdsignInActionPerformed

     private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
          dispose();
     }//GEN-LAST:event_btnQuitActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Background background1;
     private custom.Button btnQuit;
     private custom.Button cmdsignIn;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JPanel jPanel1;
     private custom.Background panelLogin;
     private custom.PasswordField textPass;
     private custom.TextField textUser;
     // End of variables declaration//GEN-END:variables
}
