
package View;

import Model.Tenant;
import Model.Contract;
import Model.ContractDAO;
import Controller.ShopController;
import Controller.TenantController;
import Controller.AccountController;
import java.time.LocalDate;

public class NewContractDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(NewContractDialog.class.getName());

    private ShopController shopController = new ShopController();
    private TenantController tenantController = new TenantController();
    private AccountController accountController = new AccountController();
    
    
    public NewContractDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          setTitle("New Contract");
          setLocationRelativeTo(parent);

          // Shop ID: 1..7
          cbShopId.setModel(new javax.swing.DefaultComboBoxModel<>(
              new String[]{"1","2","3","4","5","6","7"}
          ));
          cbShopId.setSelectedIndex(-1); // chưa chọn gì

          // Status: đúng ENUM trong DB
          cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(
              new String[]{"active"}
          ));

          clearForm(); // bắt đầu ở trạng thái trống
          reloadShopIdCombo();
          initComboDate();
    }

    private void reloadShopIdCombo() {
          try {
              cbShopId.removeAllItems();
              java.util.List<Integer> free = ContractDAO.listFreeShopIds();
              for (Integer id : free) {
                  cbShopId.addItem(String.valueOf(id)); // cbShopId là JComboBox<String>
              }
              boolean empty = free.isEmpty();
              cbShopId.setEnabled(!empty);
              if (btnSave != null) btnSave.setEnabled(!empty);
              if (empty) {
                  javax.swing.JOptionPane.showMessageDialog(this,
                      "Trung tâm còn còn shop trống để thuê!.",
                      "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
              }
          } catch (Exception ex) {
              javax.swing.JOptionPane.showMessageDialog(this,
                  "Lỗi tải danh sách shop: " + ex.getMessage(),
                  "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
          }
      }
    
    private void initComboDate(){
         //Ngày
         for(int i=1; i<=31; i++){
              cboStartDay.addItem(String.valueOf(i));
              cboEndDay.addItem(String.valueOf(i));
         }
         
         // Tháng
         for (int i = 1; i <= 12; i++) {
               cboStartMonth.addItem(String.valueOf(i));
               cboEndMonth.addItem(String.valueOf(i));
         }

         // Năm
         int currentYear = LocalDate.now().getYear();
         for (int y = currentYear; y <= currentYear + 10; y++) {
               cboStartYear.addItem(String.valueOf(y));
               cboEndYear.addItem(String.valueOf(y));
         }

         cboStartDay.setSelectedItem(String.valueOf(LocalDate.now().getDayOfMonth()));
         cboStartMonth.setSelectedItem(String.valueOf(LocalDate.now().getMonthValue()));
         cboStartYear.setSelectedItem(String.valueOf(currentYear));
         
         cboEndDay.setSelectedItem(String.valueOf(LocalDate.now().getDayOfMonth()));
         cboEndMonth.setSelectedItem(String.valueOf(LocalDate.now().getMonthValue()));
         cboEndYear.setSelectedItem(String.valueOf(currentYear));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          txtTenantId = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          cbShopId = new javax.swing.JComboBox<>();
          txtName = new javax.swing.JTextField();
          txtPhone = new javax.swing.JTextField();
          txtEmail = new javax.swing.JTextField();
          txtIncome = new javax.swing.JTextField();
          cbStatus = new javax.swing.JComboBox<>();
          jLabel10 = new javax.swing.JLabel();
          txtType = new javax.swing.JTextField();
          btnReset = new custom.Button();
          btnSave = new custom.Button();
          btnCancel = new custom.Button();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          txtShopName = new javax.swing.JTextField();
          cboStartDay = new javax.swing.JComboBox<>();
          cboStartMonth = new javax.swing.JComboBox<>();
          cboStartYear = new javax.swing.JComboBox<>();
          cboEndDay = new javax.swing.JComboBox<>();
          cboEndMonth = new javax.swing.JComboBox<>();
          cboEndYear = new javax.swing.JComboBox<>();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel1.setText("Mã khách thuê (TenantId):");

          txtTenantId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel2.setText("Mã shop muốn thuê(ShopId):");

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel3.setText("Tên khách thuê:");

          jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel4.setText("Số điện thoại:");

          jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel5.setText("Email:  ");

          jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel6.setText("Ngày bắt đầu:");

          jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel7.setText("Ngày kết thúc:");

          jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel8.setText("Tiền thuê hàng tháng:");

          jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel9.setText("Trạng thái:");

          cbShopId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          cbShopId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

          txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          txtIncome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          cbStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã thuê", "Trống" }));

          jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel10.setText("Loại hình buôn bán:");

          txtType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          btnReset.setBackground(new java.awt.Color(0, 153, 255));
          btnReset.setForeground(new java.awt.Color(255, 255, 255));
          btnReset.setText("Làm mới");
          btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnReset.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnResetActionPerformed(evt);
               }
          });

          btnSave.setBackground(new java.awt.Color(0, 153, 255));
          btnSave.setForeground(new java.awt.Color(255, 255, 255));
          btnSave.setText("Lưu");
          btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnSave.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSaveActionPerformed(evt);
               }
          });

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel11.setText("THÔNG TIN HỢP ĐỒNG THUÊ GIAN HÀNG");

          jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel13.setText("Tên Shop:");

          txtShopName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel12)
                    .addGap(46, 46, 46)
                    .addComponent(jLabel11)
                    .addContainerGap(67, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtShopName))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIncome))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbShopId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTenantId))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPhone))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(113, 113, 113))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(20, 20, 20))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboEndDay, 0, 1, Short.MAX_VALUE)))
                              .addGap(12, 12, 12)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(cboEndMonth, 0, 1, Short.MAX_VALUE)
                                   .addComponent(cboStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(cboStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(cboEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(120, 120, 120))))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel12)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel11)))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(txtTenantId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(cbShopId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtShopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel10)
                         .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel6)
                         .addComponent(cboStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(cboEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel8)
                         .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel9)
                         .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents
     public int createdId = -1;
     private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
          clearForm();
          reloadShopIdCombo();
          cbStatus.setSelectedIndex(0); // chọn lại 'active'

          // Đưa con trỏ vào ô tenant để nhập ngay
          txtTenantId.requestFocus();
     }//GEN-LAST:event_btnResetActionPerformed

     private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
          try {
          // ===== 1) VALIDATION CƠ BẢN =====
          if (txtTenantId.getText().trim().isEmpty())
              throw new IllegalArgumentException("Tenant ID không được trống");
          if (cbShopId.getSelectedIndex() < 0)
              throw new IllegalArgumentException("Hãy chọn Shop ID (1-7)");
          if (txtName.getText().trim().isEmpty())
              throw new IllegalArgumentException("Tên khách thuê không được trống");
          if (txtShopName.getText().trim().isEmpty())
              throw new IllegalArgumentException("tên Shop không được trống");
          if (txtType.getText().trim().isEmpty())
              throw new IllegalArgumentException("Loại hình không được trống");
          if (txtIncome.getText().trim().isEmpty())
              throw new IllegalArgumentException("Income không được trống");
          if(tenantController.existsById(Integer.parseInt(txtTenantId.getText())))
               throw new IllegalArgumentException("Tenant ID đã tồn tại");
          // ===== 2) LẤY DỮ LIỆU TỪ FORM =====
          Contract x = new Contract();

          // tenant nhập tay (JTextField)
          x.tenantId = Long.parseLong(txtTenantId.getText().trim());

          // shop_id từ combobox (1→7)
          Object sel = cbShopId.getSelectedItem();
          int shopId;
          if (sel instanceof String s) {
              shopId = Integer.parseInt(s.trim());
          } else {
              // phòng trường hợp bạn để model là Integer
              shopId = (Integer) sel;
          }
          x.shopId = shopId;

          x.name      = txtName.getText().trim();
          x.phone     = txtPhone.getText().trim();
          x.email     = txtEmail.getText().trim();
          x.shopName  = txtShopName.getText().trim();
          x.type      = txtType.getText().trim();

          // ngày: 
          String start = cboStartYear.getSelectedItem().toString() + "-" + cboStartMonth.getSelectedItem().toString() + "-" + cboStartDay.getSelectedItem().toString();
          String end = cboEndYear.getSelectedItem().toString() + "-" + cboEndMonth.getSelectedItem().toString() + "-" + cboEndDay.getSelectedItem().toString();
          x.startDate = java.sql.Date.valueOf(start);
          x.endDate   = java.sql.Date.valueOf(end);
          
          //ngày hiện tại
          java.sql.Date today = new java.sql.Date(System.currentTimeMillis());
          
          //start_date phải > ngày hôm nay
          if(x.startDate.before(today)){
               throw new IllegalArgumentException("start_date phải sau hôm nay");
          }
          
          //end_date phải lớn hơn start_date
          if (!x.endDate.after(x.startDate)) {
              throw new IllegalArgumentException("end_date phải lớn hơn start_date");
          }

          // tiền
          x.income = new java.math.BigDecimal(txtIncome.getText().trim());

          // status
          x.status = cbStatus.getSelectedItem().toString();

          // ===== 3) INSERT DB =====
          createdId = ContractDAO.insertReturningId(x);

          //Chỉnh sửa Trạng thái Shop theo shopId trong hợp đồng
          shopController.updateShopById(x.shopId, x.shopName, x.type, (int)x.tenantId, createdId);
          
          //Thêm khách thuê mới sau khi nhập hợp đồng
          Tenant newTenant = new Tenant((int)x.tenantId, x.name, x.phone, x.email);
          newTenant.setContractId(createdId);
          newTenant.setShopId(x.shopId);
          newTenant.setUsername("tenant" + Integer.toString((int)x.tenantId));
          newTenant.setPassword("123456");
          tenantController.createTenant(newTenant);
          
          //Thêm 1 tài khoản đăng nhập cho khách hàng
          //user name = tenant + tenantId
          //password mặc định = 123456
          accountController.registerTenant("tenant" + Long.toString(x.tenantId), "123456", x.name);
          
          javax.swing.JOptionPane.showMessageDialog(this,
                  "Đã lưu! contract_id = " + createdId);

          //Reset lại 
          clearForm();
          reloadShopIdCombo();
          cbStatus.setSelectedIndex(0); // chọn lại 'active'

          // Đưa con trỏ vào ô tenant để nhập ngay
          txtTenantId.requestFocus();
          // Tùy chọn:
          // - Nếu muốn nhập tiếp → gọi btnAddActionPerformed(null);
          // - Nếu muốn đóng luôn dialog sau khi lưu:
          // dispose();

      } catch (NumberFormatException nfe) {
          javax.swing.JOptionPane.showMessageDialog(this,
              "Sai định dạng số ở Tenant ID / Shop ID / Income",
              "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
      } catch (IllegalArgumentException iae) {
          javax.swing.JOptionPane.showMessageDialog(this,
              iae.getMessage(), "Cần nhập đúng", javax.swing.JOptionPane.WARNING_MESSAGE);
      } catch (Exception ex) {
          javax.swing.JOptionPane.showMessageDialog(this,
              "Lỗi: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
      }
     }//GEN-LAST:event_btnSaveActionPerformed

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewContractDialog dialog = new NewContractDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnReset;
     private custom.Button btnSave;
     private javax.swing.JComboBox<String> cbShopId;
     private javax.swing.JComboBox<String> cbStatus;
     private javax.swing.JComboBox<String> cboEndDay;
     private javax.swing.JComboBox<String> cboEndMonth;
     private javax.swing.JComboBox<String> cboEndYear;
     private javax.swing.JComboBox<String> cboStartDay;
     private javax.swing.JComboBox<String> cboStartMonth;
     private javax.swing.JComboBox<String> cboStartYear;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JTextField txtEmail;
     private javax.swing.JTextField txtIncome;
     private javax.swing.JTextField txtName;
     private javax.swing.JTextField txtPhone;
     private javax.swing.JTextField txtShopName;
     private javax.swing.JTextField txtTenantId;
     private javax.swing.JTextField txtType;
     // End of variables declaration//GEN-END:variables

   private void clearForm() {
    // Text fields về rỗng
    txtTenantId.setText("");
    txtName.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    txtIncome.setText("");
    txtType.setText("");

    // ComboBox về trạng thái chưa chọn (hoặc chọn mặc định)
    if (cbShopId.getItemCount() > 0) cbShopId.setSelectedIndex(-1);

    // Nếu bạn muốn model là các trạng thái trong DB:
    // cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active" }));
    if (cbStatus.getItemCount() > 0) cbStatus.setSelectedIndex(-1);
}

}
