
package View;

import Model.Tenant;
import Model.Shop;
import Model.Contract;
import Model.ContractDAO;
import Controller.TenantController;
import Controller.ShopController;
import Model.Tenant;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicSplitPaneUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;



public class TenantView extends javax.swing.JFrame {

     private TenantController tenantController = new TenantController();
     private ShopController shopController = new ShopController();
     
     public TenantView() {
          initComponents();
          
          // chỉnh độ rộng cột ở đây
          tableTenant.getColumnModel().getColumn(0).setPreferredWidth(25);
          tableTenant.getColumnModel().getColumn(1).setPreferredWidth(125);
          tableTenant.getColumnModel().getColumn(2).setPreferredWidth(100);
          tableTenant.getColumnModel().getColumn(3).setPreferredWidth(180);
          
          tableTenant.setFillsViewportHeight(true);
          
          // Sau khi gọi initComponents();
          ((BasicSplitPaneUI) jSplitPane1.getUI()).getDivider().setBackground(Color.DARK_GRAY);
          jSplitPane1.setDividerSize(7); // mặc định ~5px
          
          setLocationRelativeTo(null);
          
          //khởi tạo click chuột
          tableTenant.addMouseListener(new MouseAdapter() {
               @Override
               public void mouseClicked(MouseEvent e) {
                    //kích vào vùng không phải bảng
                   if (!tableTenant.getBounds().contains(e.getPoint())) {
                         tableTenant.clearSelection(); // Bỏ chọn dòng
                         clearContractInfo();          // Xóa thông tin hiển thị
                     }
               }
           });
          
          //thay đổi lựa chọn
          tableTenant.getSelectionModel().addListSelectionListener(e -> {
          if (!e.getValueIsAdjusting()) {
              int row = tableTenant.getSelectedRow();
                   if (row != -1) {
                       // Lấy ID khách thuê từ bảng
                       int tenantId = Integer.parseInt(tableTenant.getValueAt(row, 0).toString());

                       //tenant tương ứng
                       Tenant t = tenantController.getTenant(tenantId);
                       //shop tương ứng
                       int shopId = t.getShopId();
                       Shop s = shopController.getShopById(shopId);
                       // Gọi controller để lấy hợp đồng
                       Contract contract = ContractDAO.findByTenantId(tenantId);

                       // Hiển thị thông tin hợp đồng
                       if (contract != null) {
                           lblContractId.setText(contract.getContractId().toString());
                           lblTenantName.setText(t.getTenantName());
                           lblSdtTenant.setText(t.getPhone());
                           lblEmailTenant.setText(t.getEmail());
                           lblShopName.setText(s.getName());
                           lblArea.setText(s.getArea());
                           lblStartDate.setText(contract.getStartDate().toString());
                           lblEndDate.setText(contract.getEndDate().toString());
                           lblRental.setText(String.valueOf(contract.getIncome()) + " VNĐ");
                       } else {
                           JOptionPane.showMessageDialog(null, "Không tìm thấy hợp đồng cho khách này!");
                       }
                   }
              } else {
                  // Không có dòng nào được chọn → clear label
                  clearContractInfo();
              }
      });

     }
     
     private void clearContractInfo() {
          lblContractId.setText("");
          lblTenantName.setText("");
          lblSdtTenant.setText("");
          lblEmailTenant.setText("");
          lblShopName.setText("");
          lblArea.setText("");
          lblStartDate.setText("");
          lblEndDate.setText("");
          lblRental.setText("");
      }


     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jSplitPane1 = new javax.swing.JSplitPane();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jLabel14 = new javax.swing.JLabel();
          jLabel15 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jLabel17 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          jLabel19 = new javax.swing.JLabel();
          jLabel20 = new javax.swing.JLabel();
          lblContractId = new javax.swing.JLabel();
          jLabel22 = new javax.swing.JLabel();
          jLabel23 = new javax.swing.JLabel();
          jLabel24 = new javax.swing.JLabel();
          lblTenantName = new javax.swing.JLabel();
          lblSdtTenant = new javax.swing.JLabel();
          lblEmailTenant = new javax.swing.JLabel();
          lblShopName = new javax.swing.JLabel();
          lblArea = new javax.swing.JLabel();
          lblStartDate = new javax.swing.JLabel();
          lblEndDate = new javax.swing.JLabel();
          lblRental = new javax.swing.JLabel();
          jPanel2 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tableTenant = new javax.swing.JTable();
          tableTenant.getTableHeader().setFont(new java.awt.Font("Time New Roman", java.awt.Font.BOLD, 12));
          btnExit = new custom.Button();
          jLabel2 = new javax.swing.JLabel();
          txtSearch = new javax.swing.JTextField();
          btnSearch = new custom.Button();
          btnAll = new custom.Button();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setMinimumSize(new java.awt.Dimension(1050, 650));

          jSplitPane1.setDividerLocation(490);

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel3.setText("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");

          jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel4.setText("Độc lập - Tự do - Hạnh phúc");

          jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel5.setText("--------------------------");

          jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel6.setText("HỢP ĐỒNG CHO THUÊ GIAN HÀNG");

          jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel7.setText("Bên cho thuê");

          jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel8.setText("Quản lý trung tâm thương mại:");

          jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel9.setText("Số điện thoại:");

          jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel10.setText("Email:");

          jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel11.setText("Bên thuê");

          jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel12.setText("Tên khách thuê:");

          jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel13.setText("Số điện thoại:");

          jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel14.setText("Email:");

          jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel15.setText("Shop đang thuê:");

          jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
          jLabel16.setText("Khu vực:");

          jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel17.setText("Ngày bắt đầu thuê:");

          jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel18.setText("Ngày kết thúc:");

          jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel19.setText("Tiền thuê hàng tháng:");

          jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel20.setText("Mã hợp đồng:");

          lblContractId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

          jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel22.setText("AD");

          jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel23.setText("0363636363");

          jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel24.setText("adminTTTM@gmail.com");

          lblTenantName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblSdtTenant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblEmailTenant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblShopName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblStartDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblEndDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          lblRental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel3))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(94, 94, 94)
                              .addComponent(jLabel4)))
                    .addGap(0, 54, Short.MAX_VALUE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(164, 164, 164)
                              .addComponent(jLabel5))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(83, 83, 83)
                              .addComponent(jLabel6))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel8)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel22))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel9)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel23))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel10)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel24))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel18)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jLabel19)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(lblRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(30, 30, 30)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addComponent(jLabel7)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblShopName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEmailTenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSdtTenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel11)
                                             .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel1)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                              .addGap(19, 19, 19)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel20)
                                   .addComponent(lblContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addComponent(jLabel7)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel8)
                                   .addComponent(jLabel22))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel9)
                                   .addComponent(jLabel23))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel24))
                              .addGap(14, 14, 14)
                              .addComponent(jLabel11)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel12)
                                   .addComponent(lblTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel13))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addGap(330, 330, 330)
                              .addComponent(lblSdtTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(lblEmailTenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15)
                         .addComponent(lblShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel18))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(58, 58, 58)
                              .addComponent(lblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel19)
                         .addComponent(lblRental, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(68, 68, 68))
          );

          jSplitPane1.setLeftComponent(jPanel1);

          tableTenant.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          tableTenant.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "ID Khách thuê", "Tên khách thuê", "Điện thoại", "Email"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, false, false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tableTenant.setPreferredSize(new java.awt.Dimension(425, 160));
          tableTenant.setRowHeight(40);
          jScrollPane1.setViewportView(tableTenant);

          btnExit.setBackground(new java.awt.Color(0, 153, 255));
          btnExit.setForeground(new java.awt.Color(255, 255, 255));
          btnExit.setText("Thoát");
          btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          btnExit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnExitActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel2.setText("Nhập thông tin");

          btnSearch.setBackground(new java.awt.Color(0, 153, 255));
          btnSearch.setForeground(new java.awt.Color(255, 255, 255));
          btnSearch.setText("Tìm kiếm");
          btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          btnSearch.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSearchActionPerformed(evt);
               }
          });

          btnAll.setBackground(new java.awt.Color(0, 153, 255));
          btnAll.setForeground(new java.awt.Color(255, 255, 255));
          btnAll.setText("Tất cả");
          btnAll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          btnAll.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAllActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap(151, Short.MAX_VALUE))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                   .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18))))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(51, 51, 51)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(113, Short.MAX_VALUE))
          );

          jSplitPane1.setRightComponent(jPanel2);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jSplitPane1)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jSplitPane1)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
          new MainView_Admin().setVisible(true);
          dispose();
     }//GEN-LAST:event_btnExitActionPerformed

     private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
          // 1. Xóa nội dung ô tìm kiếm
          txtSearch.setText("");
          
          DefaultTableModel model = (DefaultTableModel) tableTenant.getModel();
          model.setRowCount(0);
          List<Tenant> tenants = tenantController.getAllTenants();
          for(Tenant t : tenants){
               model.addRow(new Object[]{
                    t.getTenantId(), t.getTenantName(),
                    t.getPhone(), t.getEmail()
               });
          }
     }//GEN-LAST:event_btnAllActionPerformed

     private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
          
          try {
               DefaultTableModel model = (DefaultTableModel) tableTenant.getModel();
               model.setRowCount(0);
               String search = txtSearch.getText();
               List<Tenant> tenants = tenantController.searchTenant(search);
               if(!tenants.isEmpty()){
                    for(Tenant t : tenants){
                         model.addRow(new Object[]{
                              t.getTenantId(), t.getTenantName(),
                              t.getPhone(), t.getEmail()
                         });
                    }
               }
               else{
                    JOptionPane.showMessageDialog(this, "Không tìm thấy khách thuê!");
               }
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin hợp lệ!");
          }
     }//GEN-LAST:event_btnSearchActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(TenantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(TenantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(TenantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(TenantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          SwingUtilities.invokeLater(() -> {
               new TenantView().setVisible(true);
           });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnAll;
     private custom.Button btnExit;
     private custom.Button btnSearch;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel22;
     private javax.swing.JLabel jLabel23;
     private javax.swing.JLabel jLabel24;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JSplitPane jSplitPane1;
     private javax.swing.JLabel lblArea;
     private javax.swing.JLabel lblContractId;
     private javax.swing.JLabel lblEmailTenant;
     private javax.swing.JLabel lblEndDate;
     private javax.swing.JLabel lblRental;
     private javax.swing.JLabel lblSdtTenant;
     private javax.swing.JLabel lblShopName;
     private javax.swing.JLabel lblStartDate;
     private javax.swing.JLabel lblTenantName;
     private javax.swing.JTable tableTenant;
     private javax.swing.JTextField txtSearch;
     // End of variables declaration//GEN-END:variables
}
