

package View;

import Model.Contract;
import Model.ContractDAO;
import java.math.BigDecimal;
import javax.swing.JOptionPane;


public class UpdateIncomeDialog extends javax.swing.JDialog {

     private ContractDAO contractDAO = new ContractDAO();
     
     public UpdateIncomeDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
          
          setLocationRelativeTo(null);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtContractId = new javax.swing.JTextField();
          txtNewIncome = new javax.swing.JTextField();
          btnCancel = new custom.Button();
          btnUpdate = new custom.Button();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resources/logomini2.png"))); // NOI18N

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Sửa tiền cho thuê");

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel3.setText("Nhập thông tin");

          jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel4.setText("Mã hợp đồng");

          jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
          jLabel5.setText("Tiền thuê");

          txtContractId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          txtNewIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
          btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
          btnUpdate.setText("Cập nhật");
          btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
          btnUpdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUpdateActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(61, 61, 61)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(62, 62, 62)
                              .addComponent(jLabel3))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(80, 80, 80)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel5)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                             .addComponent(txtNewIncome))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel4)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                             .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                              .addGap(18, 18, 18)
                              .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(70, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(17, 17, 17)
                              .addComponent(jLabel2)
                              .addGap(18, 18, 18)
                              .addComponent(jLabel3)))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(txtNewIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed

     private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          try {
               int contractId = Integer.parseInt(txtContractId.getText());
               BigDecimal income = BigDecimal.valueOf(Double.parseDouble(txtNewIncome.getText()));
               Contract c = ContractDAO.findById(contractId);
               if (c != null) {
                   int confirm = JOptionPane.showConfirmDialog(
                         this,
                         "Sửa tiền thuê của hợp đồng này?",
                         "Cập nhật tiền thuê",
                         JOptionPane.YES_NO_OPTION
                 );
                 if (confirm == JOptionPane.YES_OPTION) {
                    contractDAO.updateIncomeById(contractId, income);

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                 }
                 else JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");   
                 txtContractId.setText("");
                 txtNewIncome.setText("");
               } else {
                   JOptionPane.showMessageDialog(this, "Không tìm thấy hợp đồng!");
               }
           } catch (NumberFormatException ex) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin hợp lệ!");
           }
     }//GEN-LAST:event_btnUpdateActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(UpdateIncomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(UpdateIncomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(UpdateIncomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(UpdateIncomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    UpdateIncomeDialog dialog = new UpdateIncomeDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnUpdate;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JTextField txtContractId;
     private javax.swing.JTextField txtNewIncome;
     // End of variables declaration//GEN-END:variables
}
