
package View;

import Model.Tenant;
import Controller.TenantController;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class UpdateInfoDialog extends javax.swing.JDialog {

     private int tenantId;
     private TenantController tenantController = new TenantController();
     
     public UpdateInfoDialog(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
          initComponents();
     }

     public UpdateInfoDialog(java.awt.Frame parent, boolean modal, int tenantId) {
          super(parent, modal);
          
          this.tenantId = tenantId;
          
          initComponents();
          Tenant t = tenantController.getTenant(tenantId);
          lblName.setText(t.getTenantName());
          
          setLocationRelativeTo(parent);
     }
     
     //kiểm tra xem số điện thoại, email nhập vào có hợp lệ không
     public static boolean isValidPhoneNumber(String phoneNumber) {
        // Biểu thức chính quy cho SĐT Việt Nam (10 số, bắt đầu bằng 0)
        String phoneRegex = "^0\\d{9}$";
        return Pattern.matches(phoneRegex, phoneNumber);
    }
     
     public static boolean isValidEmail(String email) {
        // Biểu thức chính quy tiêu chuẩn cho email
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        return Pattern.matches(emailRegex, email);
    }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          btnCancel = new custom.Button();
          btnUpdate = new custom.Button();
          txtSDT = new javax.swing.JTextField();
          txtEmail = new javax.swing.JTextField();
          lblName = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
          jLabel1.setText("Cập nhật thông tin");

          jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel2.setText("Cập nhật thông tin cho:");

          jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel3.setText("Số điện thoại:");

          jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel4.setText("Email:");

          btnCancel.setBackground(new java.awt.Color(0, 153, 255));
          btnCancel.setForeground(new java.awt.Color(255, 255, 255));
          btnCancel.setText("Hủy");
          btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
          btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
          btnUpdate.setText("Cập nhật");
          btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          btnUpdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUpdateActionPerformed(evt);
               }
          });

          lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

          jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel5.setText("Thông tin cập nhật");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 90, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel3)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtSDT))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(17, 17, 17)))
                    .addGap(18, 18, 18)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69))
               .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel5)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addContainerGap())))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          dispose();
     }//GEN-LAST:event_btnCancelActionPerformed

     private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          try {
               //Nếu ko nhập gì = rỗng -> bỏ qua không cập nhật
               String phone = txtSDT.getText().trim();
               String email = txtEmail.getText().trim();
               boolean confirm = true;
               if(!phone.equals("")){
                    if(isValidPhoneNumber(phone)){
                         tenantController.updatePhoneById(tenantId, phone);
                    }
                    else{
                         confirm = false;
                         JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số điện thoại hợp lệ");
                    }
               }
               if(!email.equals("")){
                    if(isValidEmail(email)){
                         tenantController.updateEmailById(tenantId, email);
                    }
                    else{
                         confirm = false;
                         JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập Email hợp lệ!");
                    }
               }
               if(confirm){
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
                    dispose();
               }
               
          } catch (Exception e) {
               JOptionPane.showMessageDialog(rootPane, "Lỗi nhập liệu!");
          }
     }//GEN-LAST:event_btnUpdateActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(UpdateInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(UpdateInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(UpdateInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(UpdateInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the dialog */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    UpdateInfoDialog dialog = new UpdateInfoDialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                         @Override
                         public void windowClosing(java.awt.event.WindowEvent e) {
                              System.exit(0);
                         }
                    });
                    dialog.setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private custom.Button btnCancel;
     private custom.Button btnUpdate;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel lblName;
     private javax.swing.JTextField txtEmail;
     private javax.swing.JTextField txtSDT;
     // End of variables declaration//GEN-END:variables
}
